services:
  db:
    image: mariadb:lts-ubi
    container_name: mariadb
    env_file: repositories/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/3306 2>/dev/null"]
      interval: 1s
      timeout: 5s
      retries: 50
    networks:
      - red

  backend:
    build:
      context: .
    container_name: backend
    env_file: repositories/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3020:8000"
    networks:
      - red

volumes:
  mysql_data:

networks:
  red:
    driver: bridge
