name: Deploy productos to servidor

on:
  push:
    branches:
      - main

env:
  HOST: ${{ secrets.HOST_NAME }}

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    # Clona el repo en el runner
    - name: Checkout code
      uses: actions/checkout@v3

    # Prepara el agente SSH
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    #Sincroniza con rsync (excluyendo .git para que no transfieras historial)
    - name: Sync code to server
      run: |
        rsync -avz --delete \
          --exclude='.git' \
          ./ laura@$HOST:/home/laura/api-productos/

    # Levanta o reinicia los contenedores en el servidor
    - name: Restart Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no laura@$HOST "
          cd /home/laura/api-productos
          docker-compose up --build -d
        "
