name: Deploy productos
on:
  push:
    branches:
      - main
env:
  HOST: ${{ secrets.HOST_NAME }}
jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy and Run FastAPI
      run: |
        ssh -o StrictHostKeyChecking=no laura@$HOST "
          cd /home/laura/api-productos
          git clone https://github.com/LauraGabrielSantes/api-productos-docker
          cd api-productos-docker
          docker-compose up --build -d
        "